export const data: string[] = [
  "Lorem ipsum dolor sit amet consectetur adipisicing elit.Voluptate distinctio eum quia saepe obcaecati ducimus aspernatur, impedit ut ea! Incidunt eveniet dignissimos quas iusto doloribus laudantium ad tempora sapiente unde, cumque esse dolore blanditiis repudiandae odit laboriosam voluptatibus praesentium.Amet nesciunt ipsa ex ipsum voluptates porro distinctio nostrum hic error consectetur nobis quis, facilis fugit ad nisi illo ipsam dicta at ea.Non recusandae aspernatur tenetur ipsum explicabo accusantium praesentium atque eius, laudantium commodi ipsam harum",
  "nostrum deserunt ut in excepturi molestiae doloremque sint eligendi dolore totam consequatur quas.Tenetur aperiam porro voluptatem iure ut quam, dolorem natus illo adipisci deserunt ratione cumque delectus, eveniet, culpa id deleniti molestias necessitatibus enim ea neque molestiae voluptate ? Temporibus at officia vitae aut quasi recusandae, debitis voluptatem voluptatum veniam corporis quas harum, ipsa mollitia, libero reprehenderit.Aliquid mollitia consequuntur delectus iusto, nemo eaque ipsum vero, nobis autem omnis dignissimos minima minus provident repellat",
  "maxime similique dolorem fugit expedita facere in obcaecati rem sint.Eligendi minus, voluptas natus repudiandae at asperiores aliquam magni ab ipsam repellat nihil officiis ullam vel libero tenetur nostrum adipisci deleniti ex corporis sed ad iste sequi non ? Quidem modi, illum accusamus nobis fugiat rerum provident aperiam impedit.Mollitia, inventore cupiditate vitae unde repudiandae quod! Eius unde eligendi nesciunt optio iusto dolores possimus nam qui aspernatur laudantium minima sed voluptatibus quis ducimus rem, alias maiores repellendus.Qui magnam illo soluta", 
  "dolores ipsam ? Totam, esse natus, necessitatibus perspiciatis voluptatem dolorum non excepturi odit atque alias iure maxime exercitationem quasi.Deleniti amet dolore nisi enim, ipsam reprehenderit repellat accusantium, dignissimos et quia, assumenda dolorem! Cum, porro.Beatae voluptatem, labore optio repudiandae ducimus dolore ad amet cumque porro fugiat fugit, nesciunt officiis iusto adipisci hic.Quod quia numquam vero tempore accusamus alias architecto optio, repudiandae distinctio magni.Reiciendis ipsam ut, velit et eaque nobis iusto soluta placeat sequi accusantium", 
  "at veritatis obcaecati ex! Deleniti aspernatur et sunt ? Saepe magni et fugit impedit corrupti at consequuntur tempora, nam adipisci quam molestiae cumque magnam, blanditiis reprehenderit minus similique eum accusamus neque voluptate dicta.Odit aliquid dolores, magni tempore doloribus unde voluptates sed, iure mollitia impedit error sint blanditiis dolore totam.Modi, facere sequi ? Unde nostrum dolore omnis culpa adipisci blanditiis eos cumque dignissimos similique magnam nemo ipsa illum nobis eveniet ducimus neque non itaque nulla, deserunt dicta explicabo.Debitis atque", 
  "cumque itaque repudiandae nobis eveniet, praesentium error unde excepturi neque animi voluptatem eum nemo sunt minus labore laudantium.Doloribus dolorem voluptatum aperiam unde soluta iusto, quidem minima excepturi, praesentium facilis nobis asperiores beatae saepe ullam consequuntur! Beatae, cumque ab ? Quis saepe id eos, laboriosam fuga expedita excepturi quas vitae! Explicabo amet nulla sunt perferendis error maxime eligendi quia, reprehenderit mollitia quos, dolores, facere perspiciatis.Tempora ipsam, voluptates earum sequi recusandae doloribus ullam quaerat ipsa voluptatem",
  "quos non quam in commodi, odio, voluptatibus laboriosam nostrum nemo quisquam eius perspiciatis assumenda ab harum! Porro corporis nisi aut quo magnam aliquid, unde quam consequuntur sapiente quos ipsa expedita fugiat quis, beatae doloribus laborum at, fugit alias nemo.Similique iste facilis aut fugiat ? Eveniet, magnam! Ipsa soluta fugit velit ad.Rerum enim voluptates ullam aut sit accusamus pariatur explicabo autem qui temporibus assumenda repellendus totam itaque voluptatibus, sequi, dolores numquam corporis.Eius voluptatibus optio sunt eum animi quo, fuga mollitia doloremque ",
  "quaerat ducimus beatae.Laboriosam, quisquam rerum eos esse cumque libero laborum, voluptate magnam ipsam, commodi dolor excepturi labore.Assumenda quasi debitis, delectus nobis, neque veniam harum iusto laborum deleniti ea quam ipsa.Explicabo, officiis natus in cumque veniam, inventore nihil beatae itaque sunt molestiae suscipit voluptate, labore adipisci optio ad quisquam minima nam sint obcaecati perspiciatis.Ea repellat beatae alias unde facere odio aliquid mollitia, nostrum nobis, iste a magni tempore consequuntur eveniet excepturi necessitatibus voluptatem dolores vel ? Optio", 
  "impedit rerum enim dicta vel, mollitia corporis repellat inventore asperiores consequatur architecto.Temporibus ipsam possimus ex suscipit sint non quasi ? Impedit distinctio modi neque nulla iusto maiores qui eum illum, culpa eos esse non adipisci quasi quidem excepturi vel est in odio ipsum accusantium.Eum cupiditate voluptatem porro placeat totam, distinctio a nihil.Fugit, accusamus, quos velit voluptatibus nihil harum blanditiis molestiae atque facilis debitis minus tempore voluptatem.Error, beatae sint.Voluptate inventore nesciunt officia dignissimos quibusdam nisi mollitia ",
  "earum illum aliquam, nostrum, cum saepe quod! Aliquid at corrupti rerum qui quisquam ullam animi enim, omnis tempore, autem voluptatum doloribus iusto.Non saepe aliquam obcaecati tenetur, fuga illo vel eaque, distinctio quisquam natus cupiditate! Sint debitis ea itaque labore dolorum libero id aut perspiciatis veniam ipsa architecto commodi beatae explicabo, a molestiae dolore corporis.Omnis quis fugiat ducimus, corrupti porro inventore sint iure deserunt praesentium modi, perferendis in sit animi id tempora unde doloremque! Itaque eos ex provident dolor voluptates, tempore nemo",
  "vitae sapiente voluptate labore, aperiam quasi, neque eligendi laborum laudantium recusandae molestiae.Ad, iusto.Adipisci mollitia culpa animi earum repudiandae, aut unde ab quibusdam perspiciatis quia ad provident beatae soluta consectetur ? Sapiente hic rerum obcaecati provident ratione itaque fugiat suscipit sint omnis est, nisi libero ipsa cumque reprehenderit odit blanditiis! A, harum molestiae quia error sint excepturi, pariatur ducimus animi debitis, dolore officiis.Quod rerum fugit harum debitis pariatur aliquam recusandae qui odit cumque placeat voluptate natus nihil maxime",
"similique ad delectus assumenda optio praesentium est omnis, magnam consectetur animi possimus quam! Deleniti cum excepturi aut facere, atque, alias nulla magnam perferendis optio quis rem enim nemo molestiae repellat libero delectus, corporis dolores dolor tenetur sunt ratione vitae cupiditate.Sint illum nesciunt velit quia excepturi commodi rerum eos esse asperiores officiis, minus vero voluptas iste, obcaecati labore culpa saepe, ipsa praesentium unde animi repudiandae fugiat cupiditate eius consectetur ? Assumenda facilis natus, veritatis minima doloribus ea mollitia.Itaque ipsa" ,
"iste corporis cupiditate accusamus hic eaque ipsum, earum, necessitatibus alias ut nihil omnis blanditiis odit impedit ipsam.Necessitatibus ad atque illo dolore.Velit, fugit quia, vero quos dolores saepe neque ex reiciendis, suscipit explicabo molestias blanditiis architecto ? Distinctio, harum.Aut magnam velit officiis! Animi maxime voluptatem nam inventore vero numquam, distinctio quibusdam impedit ipsam qui quasi consequatur voluptates magnam Lorem ipsum dolor sit amet consectetur adipisicing elit. Et architecto voluptatibus, quam fuga porro asperiores blanditiis assumenda"
];
